// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
  IntelliQ_CACHE_VERSION: KVNamespace;
  id: 'e4ba004cd93a4e25853e135da77c9509';
  ADMIN_TOKEN: string;
  API_URL: string;
  AWS_ACCESS_KEY_ID: string;
  AWS_SECRET_ACCESS_KEY: string;
  DATABASE_URL: string;
  GPT_MODEL: string;
  OPENAI_API_KEY: string;
  QSTASH_TOKEN: string;
  SUPABASE_ANON_KEY: string;
  SUPABASE_URL: string;
  UPSTASH_REDIS_REST_TOKEN: string;
  UPSTASH_REDIS_REST_URL: string;
  HYPERDRIVE: Hyperdrive;
}
