// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	NEXT_PUBLIC_SUPABASE_URL: string;
	NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
	DATABASE_URL: string;
	NEXT_PUBLIC_BASE_URL: string;
	OPENAI_API_KEY: string;
	GPT_MODEL: string;
	AMAZON_REGION: string;
	AMAZON_ACCESS_KEY_ID: string;
	AMAZON_SECRET_ACCESS_KEY: string;
	UPSTASH_REDIS_REST_URL: string;
	UPSTASH_REDIS_REST_TOKEN: string;
	HYPERDRIVE: Hyperdrive;
}
