// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
	DATABASE_URL: string;
	OPENAI_API_KEY: string;
	GPT_MODEL: string;
	UPSTASH_REDIS_REST_URL: string;
	UPSTASH_REDIS_REST_TOKEN: string;
	HYPERDRIVE: Hyperdrive;
}
