// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	IntelliQ_CACHE_VERSION: KVNamespace;
	ENVIRONMENT: "development";
	id: "e4ba004cd93a4e25853e135da77c9509";
	DATABASE_URL: string;
	GPT_MODEL: string;
	OPENAI_API_KEY: string;
	SUPABASE_ANON_KEY: string;
	SUPABASE_URL: string;
	UPSTASH_REDIS_REST_TOKEN: string;
	UPSTASH_REDIS_REST_URL: string;
}
