name = "api"
main = "src/index.ts"
compatibility_date = "2025-01-16"

compatibility_flags = [ "nodejs_compat" ]

[vars]
GPT_MODEL="gpt-4o-mini"
# ENVIRONMENT="development"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "e4ba004cd93a4e25853e135da77c9509"

[observability.logs]
enabled = false
